### ISSUE TITLE
Questions about the datasets

### ISSUE THREAD

**Issue by Xu107** [xyliugo/ODMT#2]
Thank you very much for your team's excellent work;

I am very interested in your method and would like to follow your work. Sincerely asking when will the dataset be open sourced? This will be very helpful in my current job, thank you very much!

 I extend my sincere gratitude for your work.

**Comment by Li-fAngyU** [comment]
same issue here!

**Comment by xyliugo** [comment]
Thank you for your attention to our work!
We have uploaded the processed Arts dataset to the repository.

**Comment by Li-fAngyU** [comment]
@xyliugo Thank you very much for your reply, but I encountered the following error while running the 1_lmdb_build.py code:
```
61817it [01:59, 516.98it/s]
Traceback (most recent call last):
  File "1_lmdb_build.py", line 63, in <module>
    txn.commit()
lmdb.InvalidParameterError: mdb_txn_commit: Invalid argument
```

This is all the files in the `data` folder:
![图片](https://github.com/xyliugo/ODMT/assets/56572498/ae3d4452-01f8-416b-9fad-4adc09d75130)

**Comment by xyliugo** [comment]
We hadn't encountered this issue before. Could you check the lmdb file? Is it still working (run 2_lmdb_read.py to test)? I observed that the lmdb file appears to have been generated successfully. If the lmdb is corrupted, it's possible that some images are damaged. You may consider manually removing them.

**Comment by Li-fAngyU** [comment]
> We hadn't encountered this issue before. Could you check the lmdb file? Is it still working (run 2_lmdb_read.py to test)? I observed that the lmdb file appears to have been generated successfully. If the lmdb is corrupted, it's possible that some images are damaged. You may consider manually removing them.

still error when i run `2_lmdb_read.py`:
```
read lmdb database
Traceback (most recent call last):
  File "2_lmdb_read.py", line 64, in <module>
    lmdb_data = DatasetLMDB(f'{dataset}_image.lmdb', resize=resize)
  File "2_lmdb_read.py", line 32, in __init__
    self.length = pickle.loads(txn.get(b'__len__'))
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by Li-fAngyU** [comment]
@xyliugo  sry, my disk space is full. I freed up some space and the problem was resolved.
