### ISSUE TITLE
to start running

### ISSUE THREAD

**Issue by kouhkh** [xyliugo/ODMT#3]
In run_arts.py,
1. Change root_data_dir to your data directory and root_model_dir to your pretrained_models directory.
2. Edit gpu_id to the IDs of your GPUs that you want to run on, master_port = randint(1, 65535)
3. There's a python path in run_py string that you are supposed to config.
4. The variable "version" appears IMT in in model.py as "cut", v2 corresponds to the version without ID mask in the paper, while v1 corresponds to full ODMT.

To save your time, I recommend saving the v and t features extracted in main.py and loading them from disk starting from the second run. Just torch.save, torch.load.
**Running 1_lmdb_build.py will tell you which files are corrupted in lmdb，the easiest way to beat the problem is deleting those ASINs in Arts_Crafts_and_Sewing_text.tsv and Arts_Crafts_and_Sewing_user_behaviours.tsv. Otherwise, you might get error while extracting visual features.**
If you are using a distributed file system and find it too slow reading from the image.lmdb, you can try extracting visual features on a PC.

**Comment by xyliugo** [comment]
Thank you for clarifying the details of our work reproduction! Your thoughtful suggestions will undoubtedly benefit others.
