### ISSUE TITLE
An Unresolved error

### ISSUE THREAD

**Issue by JF-BAI** [xyliugo/ODMT#7]
![微信截图_20240416135402](https://github.com/xyliugo/ODMT/assets/142509243/bccf16e2-8cbf-417d-9918-2b958d637ed6)
 **I ran the file——2_lmdb_read.py,An error has occurred as shown in the figure.Can you tell me your method of correction？thank you ！！！**
![code](https://github.com/xyliugo/ODMT/assets/142509243/210050a1-a5ec-4265-85cc-a1da988060df)

**Comment by xyliugo** [comment]
Check #2 and #3. Maybe some files are corrupted, and you need to remove them manually. I also have no idea which file has the problem, it seems a bit random and I'm not familiar with these things (sry).
